// Package notify emits GitHub Actions annotations, PR comments, and Slack messages.
package notify

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/srivarenya01/DepScan/internal/reporter"
)

// GithubAnnotations prints ::error / ::warning lines for GitHub Actions.
func GithubAnnotations(results []reporter.Result) {
	for _, r := range results {
		if r.Analysis == nil {
			continue
		}
		switch strings.ToUpper(r.Analysis.Verdict) {
		case "BREAKING":
			fmt.Printf("::error title=BREAKING %s::%s %s->%s - %s\n",
				r.Package, r.Package, r.Current, r.Latest, r.Analysis.Summary)
		case "CAUTION":
			fmt.Printf("::warning title=CAUTION %s::%s %s->%s - %s\n",
				r.Package, r.Package, r.Current, r.Latest, r.Analysis.Summary)
		}
	}
}

// PRComment prints a complete markdown PR comment body to stdout.
func PRComment(results []reporter.Result) {
	var sb strings.Builder
	sb.WriteString("## depscan - Dependency Safety Report\n\n")
	sb.WriteString("| Package | Upgrade | Verdict | Summary |\n")
	sb.WriteString("|---------|---------|---------|--------|\n")
	for _, r := range results {
		if r.Analysis == nil {
			continue
		}
		fmt.Fprintf(&sb, "| `%s` | `%s` -> `%s` | **%s** | %s |\n",
			r.Package, r.Current, r.Latest,
			r.Analysis.Verdict, r.Analysis.Summary)
	}
	sb.WriteString("\n---\n*Generated by [depscan](https://github.com/srivarenya01/DepScan)*\n")
	fmt.Println(sb.String())
}

// Slack posts a summary to a Slack incoming webhook URL.
func Slack(webhookURL string, results []reporter.Result) error {
	var breaking, caution, safe []string
	for _, r := range results {
		if r.Analysis == nil {
			continue
		}
		line := fmt.Sprintf("`%s` %s->%s", r.Package, r.Current, r.Latest)
		switch strings.ToUpper(r.Analysis.Verdict) {
		case "BREAKING":
			breaking = append(breaking, line)
		case "CAUTION":
			caution = append(caution, line)
		case "SAFE":
			safe = append(safe, line)
		}
	}

	var sections []map[string]interface{}
	sections = append(sections, map[string]interface{}{
		"type": "section",
		"text": map[string]string{"type": "mrkdwn", "text": "*depscan* - Dependency Safety Report"},
	})
	if len(breaking) > 0 {
		sections = append(sections, map[string]interface{}{
			"type": "section",
			"text": map[string]string{"type": "mrkdwn",
				"text": "[BREAKING] - manual action required:\n• " + strings.Join(breaking, "\n• ")},
		})
	}
	if len(caution) > 0 {
		sections = append(sections, map[string]interface{}{
			"type": "section",
			"text": map[string]string{"type": "mrkdwn",
				"text": "[CAUTION] - review before merging:\n• " + strings.Join(caution, "\n• ")},
		})
	}
	if len(safe) > 0 {
		sections = append(sections, map[string]interface{}{
			"type": "section",
			"text": map[string]string{"type": "mrkdwn",
				"text": fmt.Sprintf("[SAFE] - %d package(s) can be updated freely.", len(safe))},
		})
	}

	payload, err := json.Marshal(map[string]interface{}{"blocks": sections})
	if err != nil {
		return err
	}
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Post(webhookURL, "application/json", bytes.NewReader(payload))
	if err != nil {
		return err
	}
	defer func() {
		io.Copy(io.Discard, resp.Body)
		resp.Body.Close()
	}()
	if resp.StatusCode != 200 {
		return fmt.Errorf("slack webhook returned HTTP %d", resp.StatusCode)
	}
	return nil
}
